//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Тестирование_персонала
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultAnswers
    {
        public int Id { get; set; }
        public int ResultId { get; set; }
        public int QuestionId { get; set; }
        public int Answer { get; set; }
    
        public virtual Results Results { get; set; }
        public virtual TestQuestions TestQuestions { get; set; }
    }
}
