//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Тестирование_персонала
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestQuestions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestQuestions()
        {
            this.ResultAnswers = new HashSet<ResultAnswers>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TestId { get; set; }
        public string Text { get; set; }
        public string Image { get; set; }
        public string Answers { get; set; }
        public Nullable<int> AnswerNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResultAnswers> ResultAnswers { get; set; }
        public virtual Tests Tests { get; set; }
    }
}
